[package]
name = "demo-sciter-js-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
sciter-rs = { version = "0.5.58", features = ["extension"] }
